nome = input("Digite seu nome completo: ")
nome_maiusculas = nome.upper()
nome_minusculas = nome.lower()
letras_s_espaco = (nome.replace(' ', ''))
letras_primeiro_nome = nome.split()
print ('Seu nome com todas as letras maiúsculas fica assim: {}'.format(nome_maiusculas))
print ('Seu nome com todas as letras minúsculas fica assim: {}'.format(nome_minusculas))
print ("Seu nome completo tem {} letras desconsiderando os espaços.".format(len(letras_s_espaco)))
print ('Seu primeiro nome tem {} letras.'.format(len(letras_primeiro_nome[0])))